#include <Misc.au3>
#Include <WinAPIEx.au3>

HotKeySet("{Esc}", "Terminate")
;~ HotKeySet("{Home}", "_Wait_Battle")
Func Terminate()
TrayTip("Подсказка", "Программа закрыта, Всего хорошего :)", 1500)
;~ ProcessClose('Bot_WOT_s.exe')
;~ 	Sleep(1000)
	Exit 0
EndFunc   ;==>TerminateS

Opt("SendKeyDelay", 300)          ;5 миллисекунд
Opt("SendKeyDownDelay", 18)      ;1 миллисекунда
Opt("WinTitleMatchMode", -4)     ;1=с началом, 2=частично, 3=точно, 4=расширено, -1 to -4=Nocase
$Title = WinGetTitle ( "VPS-" ) ;часть имени окна
;~ $Title = WinGetTitle ( "speed" ) ;часть имени окна
ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $Title = ' & $Title & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
$hwnd=WinGetHandle($Title)
WinActivate($hwnd)
dim $send
;~ $send = 'sudo nano /etc/ppp/pptpd-options'
;~ $send = 'sudo nano /etc/pptpd.conf'


;~ $send = 'sudo apt-get update'
;~ $send = 'sudo apt-get install pptp'
;~ $send = 'sudo iptables -A POSTROUTING -t nat -s 192.168.1.0/24 -j MASQUERADE'
;~ $send = 'sudo nano /etc/iptables.rules'
;~ $SEND = '# Generated by iptables-save v1.4.10 on Sat Nov 24 15:25:31 2012{Enter}*nat{Enter}:PREROUTING ACCEPT [258:34197]{Enter}:POSTROUTING ACCEPT [0:0]{Enter}:OUTPUT ACCEPT [0:0]{Enter}-A POSTROUTING -s 192.168.1.0/24 -j MASQUERADE{Enter}COMMIT{Enter}# Completed on Sat Nov 24 15:25:31 2012{Enter}# Generated by iptables-save v1.4.10 on Sat Nov 24 15:25:31 2012{Enter}*mangle{Enter}:PREROUTING ACCEPT [3940:519430]{Enter}:INPUT ACCEPT [1870:247749]{Enter}:FORWARD ACCEPT [1985:253088]{Enter}:OUTPUT ACCEPT [1057:150925]{Enter}:POSTROUTING ACCEPT [3042:404013]{Enter}COMMIT{Enter}# Completed on Sat Nov 24 15:25:31 2012{Enter}# Generated by iptables-save v1.4.10 on Sat Nov 24 15:25:31 2012{Enter}*filter{Enter}:INPUT ACCEPT [1870:247749]{Enter}:FORWARD ACCEPT [1985:253088]{Enter}:OUTPUT ACCEPT [1057:150925]{Enter}COMMIT{Enter}# Completed on Sat Nov 24 15:25:31 2012'
;~ $SEND = '# Generated by iptables-save v1.4.10 on Sat Nov 24 15:25:31 2012{Enter}*nat{Enter}:PREROUTING ACCEPT [258:34197]'
;~ $send = 'sudo nano /etc/init.d/pptpd'
;~ $send = 'iptables-restore < /etc/iptables.rules'
;~ $send = 'sudo nano /etc/sysctl.conf'
;~ $send = 'net.inet.gre.allow=1'
;~ $send = 'sudo nano /etc/ppp/chap-secrets'
;~ $send = 'test * test *'
;~ $send = 'sudo service pptpd restart'
;~ $send = 'sudo ethtool eth0'
;~ $send = 'sudo apt-get install python-pip'
;~ $send = 'sudo pip install speedtest-cli'
;~ $send = 'logfile /var/log/pptpd.log'
;~ $send = 'sudo nano /var/log/pptpd.log'

;Попытки починить предыдущий вариант
;~ $send = 'localip 192.168.1.1'
;~ $send = ':POSTROUTING ACCEPT [0:0]'
;~ $send = 'modprobe ppp_mppe'
;~ $send = '# IP-adres servera v loqal`noi` seti'
;~ $send = 'localip 176.120.25.26'
;~ $send = '# Diapazon adresov dlia clientov PPTP-servera'
;~ $send = 'remoteip 176.120.25.200-254'
;~ $send = 'sudo nano /etc/iptables.rules'
;~ $send = '# Razreshaem protoqol GRE dlia vsekh;'
;~ $send = 'sudo iptables -A INPUT -p gre -j ACCEPT'
;~ $send = '# Razreshaem soedinenie s PPTP-serverom dlia vsekh;'
;~ $send = 'sudo iptables -A INPUT -m tcp -p tcp –-dport 1723 -j ACCEPT'
;~ $send = 'sudo nano /home/nat'
;~ $send = '#!/bin/bash|echo "1" > /proc/sys/net/ipv4/ip_forward|echo 1 > /proc/sys/net/ipv4/ip_dynaddr|modprobe iptable_nat|modprobe ip_conntrack_ftp|modprobe ip_nat_ftp|iptables --table nat --append POSTROUTING --out-interface eth0 -j MASQUERADE|iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu'
;~ $send = 'sudo chmod +x /home/nat'
;~ $send = 'sudo /home/nat'
;~ $send = '/etc/init.d/pptpd restart'

; Прочее
;~ $send = 'sudo nano /etc/apt/sources.list'

;~ $send = 'sudo iperf -c iperf.eltel.net'
;~ $send = 'sudo iperf -c speedcheck.gldn.net -u -t 10 -i 1 -b 1M'
;~ $send = 'sudo iperf -c speedtest.net -p 80'
;~ $send = 'sudo iperf -c netflow01.acd.net -n 100000'
;~ $send = 'sudo iperf -c 69.63.233.182 -r'
;~ $send = 'sudo iperf -c iperf.scottlinux.com'
;~ $send = 'sudo iperf -c iperf.saratov.ertelecom.ru'


; Debian 7 pppoE
;~ $send = 'aptitude update'
;~ $send = 'aptitude install openssh-server mc mtr tracert nano tcpdump bind9 pppoe freeradius radiusclient1 rcconf php5'
;~ $send = 'nano /etc/bind/named.conf.options'
;~ $send = 'allow-transfer { none; };|allow-query { 10.128.0.0/16; localhost; }; //podset` nashikh pol`zovatelei`|allow-recursion { 10.128.0.0/16; localhost; }; //rekursiia tol`ko lokal`ny`m|version "My ISP DNS"; //skry`li informatciiu o versii servera'
;~ $send = 'mkdir -p /root-dns/etc'
;~ $send = 'mkdir /root-dns/dev'
;~ $send = 'mkdir -p /root-dns/var/cache/bind'
;~ $send = 'mkdir -p /root-dns/var/run/bind/run'
;~ $send = '/etc/init.d/bind9 stop'
;~ $send = 'nano /etc/default/bind9'
;~ $send = 'OPTIONS="-u bind -t /root-dns"'
;~ $send = 'mv /etc/bind /root-dns/etc'
;~ $send = 'ln -s /root-dns/etc/bind /etc/bind'
;~ $send = 'nano /etc/init.d/bind9'
;~ $send = 'OPTIONS="-u bind -t /root-dns"'
;~ $send = 'nano /etc/init.d/rsyslogd'
;~ $send = 'RSYSLOGD_OPTIONS="-c3 -a /root-dns/dev/log"'
;~ $send = 'chattr +i /root-dns/etc/bind/named.conf'
;~ $send = 'mknod /root-dns/dev/null c 1 3'
;~ $send = 'mknod /root-dns/dev/random c 1 8'
;~ $send = 'chmod 666 /root-dns/dev/null /root-dns/dev/random'
;~ $send = 'chown -R bind:bind /root-dns/var/*'
;~ $send = 'chattr -i /root-dns/etc/bind/named.conf'
;~ $send = 'chown -R bind:bind /root-dns/etc/bind'
;~ $send = '/etc/init.d/bind9 start'






$send = StringReplace($send,'}','IOPTHN')
$send = StringReplace($send,'{','{shiftdown}{{}{shiftup}')
$send = StringReplace($send,'IOPTHN','{shiftdown}]{shiftup}')
$send = StringReplace($send,'!','{!}')
$send = StringReplace($send,'+','{+}')
$send = StringReplace($send,'^','{+}')
$send = StringReplace($send,':','Ж')
$send = StringReplace($send,';','ж')
$send = StringReplace($send,'"','Э')
$send = StringReplace($send,'#','+3')
$send = StringReplace($send,'/','{NUMPADDIV}')
$send = StringReplace($send,'.','{NUMPADDOT}')
;~ send('{sHIFTUP}')
;~ _SplitSend($SEND,'|',0)
;~ {ASC nnnn} Чтобы эмулировать ASCII символ A

;~ controlsend($hwnd,'','',$SEND )
;~ exit
;~ _auth(1)
;~ _auth()
;SCROLLLOCK
;0 - выключен, 1 - включен
If _WinAPI_GetKeyState(0x91) = 0 Then

Else
    _auth(1)
EndIf

_CommentUncommentAllFile(1)
;~ _SplitSend($SEND)
;~ exit

sleep(100)
;~ send('{CAPSLOCK OFF}')
ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $send = ' & $send & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
send($send)
sleep(500)
;~ send("{Enter}")

Func _SplitSend($sendForSplit,$delimeters='{Enter}',$flag=1)
	ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $sendForSplit = ' & $sendForSplit & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
	sleep(100)
	 $SendSplit = StringSplit($sendForSplit,$delimeters,$flag)
		 ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : Ubound($SendSplit) = ' & Ubound($SendSplit) & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
		 send('{CAPSLOCK off}')
	 for $i=1 to Ubound($SendSplit) - 1
;~ 		 $len = StringLen($SendSplit[$i])-2
;~ 		 ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $len = ' & $len & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
;~ 		 send(StringMid($SendSplit[$i],2,$len))
		 send($SendSplit[$i])
		 ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $SendSplit[$i] = ' & $SendSplit[$i] & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
		 sleep(500)
		 send('{ENTER}')
		 sleep(500)
	 next
	 exit
endfunc

Func _CommentUncommentAllFile($mod=0)
	sleep(100)
	send('{CAPSLOCK off}')
	while 1
		send('{home}')
		if $mod=1 then
			send('Ж')
			send('{#}')
		Else
;~ 			send('{BS}')
			send('{DEL}')
		EndIf

		send('{down}')
		sleep(350)
	WEnd
EndFunc


Func _auth($mod=0)
	ConsoleWrite("Ввод пароля " &@CRLF)
;~ 	if $mod=0 then send("root{Enter}")
	if $mod=0 then send("administrator{Enter}")
;~ 	send("admin{Enter}")
;~ 	send("user{Enter}")
	sleep(500)
	send("yjds1_")
	sleep(500)
	send("gfh0km")
	sleep(500)
	send("{Enter}")


ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : send("{Enter}") = ' & send("{Enter}") & @CRLF & '>Error code: ' & @error & @CRLF) ;### Debug Console
Exit
EndFunc
